/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.33
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.siteview.jsvapi;

public class swig {
  public static boolean swig_GetUnivData(ForestMap fmap, StringMap inwhat, MyString estr) {
    return swigJNI.swig_GetUnivData(ForestMap.getCPtr(fmap), fmap, StringMap.getCPtr(inwhat), inwhat, MyString.getCPtr(estr), estr);
  }

  public static boolean swig_SubmitUnivData(ForestMap fmap, StringMap inwhat, MyString estr) {
    return swigJNI.swig_SubmitUnivData(ForestMap.getCPtr(fmap), fmap, StringMap.getCPtr(inwhat), inwhat, MyString.getCPtr(estr), estr);
  }

  public static boolean swig_GetForestData(ForestVector fvec, StringMap inwhat, MyString estr) {
    return swigJNI.swig_GetForestData(ForestVector.getCPtr(fvec), fvec, StringMap.getCPtr(inwhat), inwhat, MyString.getCPtr(estr), estr);
  }

  public static boolean swig_SNextKey(StringMap inwhat, MyString key, MyBool first) {
    return swigJNI.swig_SNextKey(StringMap.getCPtr(inwhat), inwhat, MyString.getCPtr(key), key, MyBool.getCPtr(first), first);
  }

  public static boolean swig_FNextKey(ForestMap fmap, MyString key, MyBool first) {
    return swigJNI.swig_FNextKey(ForestMap.getCPtr(fmap), fmap, MyString.getCPtr(key), key, MyBool.getCPtr(first), first);
  }

}
